django/todo/login/urls.py
from django.urls import path

from . import views


app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

django/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('login.urls')),
    path('todo/', include('todoapp.urls')),
    path('admin/', admin.site.urls),
]

django/todo/todoapp/urls.py
from django.urls import path

from . import views


app_name = 'todoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>', views.details, name="details"),
    path('new', views.new, name="new"),
]

django/todo/login/models.py
from django.db import models

# Create your models here.

django/todo/todoapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    completed = models.BooleanField()

    def __str__(self):
        return self.text

django/todo/login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import reverse


def login(request):

    context = {}

    if request.method == 'POST':
        user = authenticate(request, username=request.POST['user'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('todoapp:index'))
        else:
            context = {
                'error': 'Wrong user name or password.'
            }

    return render(request, 'login/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login:login'))


def signup(request):
    pass

django/todo/todoapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse

from .models import Todo


@login_required
def index(request):
    todos = Todo.objects.filter(user=request.user)
    context = {
        'todos': todos
    }
    return render(request, 'todoapp/index.html', context)


def details(request, pk):
    todo = get_object_or_404(Todo, pk=pk)

    if request.method == 'GET':
        context = {
            'todo': todo
        }
        return render(request, 'todoapp/details.html', context)

    if request.method == 'POST':
        todo.text = request.POST['text']
        completed = request.POST.getlist('completed')
        if len(completed) > 0:
            todo.completed = True
        else:
            todo.completed = False
        todo.save()
        return HttpResponseRedirect(reverse('todoapp:index'))

    return HttpResponseBadRequest()

def new(request):
    if request.method == 'GET':
        return render(request, 'todoapp/new.html')

    if request.method == 'POST':
        todo = Todo()
        todo.user = request.user
        todo.text = request.POST['text']
        completed = request.POST.getlist('completed')
        if len(completed) > 0:
            todo.completed = True
        else:
            todo.completed = False
        todo.save()
        return HttpResponseRedirect(reverse('todoapp:index'))

    return HttpResponseBadRequest()

django/todo/login/templates/login/login.html
<h1>Login</h1>

<form action="." method="post">
    {% csrf_token %}
    <input type="text" name="user" placeholder="User Name">
    <input type="password" name="password" placeholder="Password">
    <button type="submit">Login</button>
</form>

{% if error  %}
    {{ error  }}
{% endif  %}

django/todo/login/templates/login/signup.html
<h1>Sign Up</h1>

django/todo/todoapp/templates/todoapp/details.html
<form action="{% url 'todoapp:details' todo.pk  %}" method="post">
    {% csrf_token %}
    <input type="text" name="text" value="{{ todo.text }}">
    <input type="checkbox" name="completed" value="1" {% if todo.completed %}checked {% endif %} >
    <button type="submit">Update</button>
</form>

django/todo/todoapp/templates/todoapp/index.html
<h1>To Dos</h1>

<ul>
{% for todo in todos  %}
    <li>
        <a href="{% url 'todoapp:details' todo.pk %}">{{ todo.text  }}</a> -- {{ todo.completed }}
    </li>
{% endfor  %}
</ul>

<a href="{% url 'todoapp:new' %}">Create new todo</a>

<a href="{% url 'login:logout' %}">Log out</a>

django/todo/todoapp/templates/todoapp/new.html
<form action="{% url 'todoapp:new'  %}" method="post">
    {% csrf_token %}
    <input type="text" name="text">
    <input type="checkbox" name="completed" value="1" >
    <button type="submit">Create New Todo</button>
</form>